version: "3.7"
services:
  server:
    build: 
      context: "."
      dockerfile: "Dockerfile"
      target: "development"
    ports:
      - "1234:12345"
    volumes:
      - .:/app
      - /app/node_modules